
spring:
  profiles:
    active:
      postgre
  jpa:
    properties:
      hibernate:
        default_schema: carcatalog
    hibernate:
      ddl-auto: none

logging:
  file:
    name: logs/log.log
  pattern:
    file: '%d{dd-MM-yyyy HH:mm:ss} [%thread] %-5level %logger{36}.%M -%msg%n'
  level:
    root: INFO
